/* ==========================================================================
   TGP.data — central configuration and mock data.

   THIS IS THE FILE THAT GETS REPLACED WHEN THE BACKEND ARRIVES.
   Everything downstream (calculations.js, charts.js, app.js) reads through
   TGP.config and TGP.data.* and never hard-codes a supplier, terminal or
   product name. When Firestore is wired in, this file's job is taken over by
   snapshot listeners that populate the same shapes — nothing else should need
   to change.

   WHAT'S REAL AND WHAT'S SYNTHETIC
   - currentPrices for Gull, Z and BP use figures actually published in each
     supplier's live document, read on 16 Aug 2026. Both the current and the
     immediately preceding effective-date block are real, because both
     appeared in the same source document.
   - Mobil's current figures are real (read from mobil.co.nz on 16 Aug 2026).
     No prior-week figure was captured, so its previousValue is left null —
     that null is itself a real UI state (first observation), not a filled gap.
   - Everything further back than one prior week, and all of the AIP series,
     is generated by a seeded random walk anchored to the real current value.
     It exists to make the History and Market tabs demonstrable, not to
     represent actual historical prices.
   - BP's Mount Maunganui rows are the sparse-data case flagged in the
     research phase (a terminal that only sells one grade leaves other cells
     blank). Coordinate-based extraction resolves this correctly, which is why
     those two rows carry extractionMethod: 'PDF_COORDINATE' instead of
     'TEXT_EXACT_ARITY'. Note there is genuinely no Premium 95 row for BP at
     Mount Maunganui — BP does not sell that grade there. That's real market
     structure, not a parsing gap.
   ========================================================================== */
(function (global) {
  'use strict';

  // ---------------------------------------------------------------- rng
  // Deterministic PRNG so the "sample" data is stable across page loads
  // (mulberry32, seeded from a string hash).
  function hashSeed(str) {
    let h = 1779033703 ^ str.length;
    for (let i = 0; i < str.length; i++) {
      h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
      h = (h << 13) | (h >>> 19);
    }
    return h >>> 0;
  }
  function mulberry32(seed) {
    let a = seed;
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  // ---------------------------------------------------------------- config
  const PRODUCTS = [
    { id: 'REGULAR_91', label: 'Regular 91', shortLabel: '91' },
    { id: 'PREMIUM_95', label: 'Premium 95', shortLabel: '95' },
    { id: 'DIESEL', label: 'Diesel', shortLabel: 'Diesel' },
  ];

  const REGIONS = [
    { id: 'AUCKLAND_WIRI', label: 'Auckland — Wiri', active: true },
    { id: 'MOUNT_MAUNGANUI', label: 'Mount Maunganui', active: true },
    // Present so the terminal selector is proven data-driven, not hard-coded
    // to two entries. Admin-activatable later; carry no price data yet.
    { id: 'MARSDEN_POINT', label: 'Marsden Point', active: false },
    { id: 'WELLINGTON', label: 'Wellington', active: false },
    { id: 'CHRISTCHURCH', label: 'Christchurch', active: false },
    { id: 'DUNEDIN', label: 'Dunedin', active: false },
  ];

  const SUPPLIERS = [
    { id: 'GULL', name: 'Gull New Zealand', sourceType: 'PDF', color: '#0f6659',
      sourceUrl: 'https://gull.nz/fuelcategorylatest/tgp/' },
    { id: 'Z', name: 'Z Energy', sourceType: 'PDF', color: '#1c7a4c',
      sourceUrl: 'https://www.z.co.nz/for-businesses/fuels-and-services/terminal-gate-pricing' },
    { id: 'BP', name: 'BP New Zealand', sourceType: 'PDF', color: '#a1311f',
      sourceUrl: 'https://www.bp.com/en_nz/new-zealand/home/products-and-services/bp-for-business/terminal-gate-purchases.html' },
    { id: 'MOBIL', name: 'Mobil', sourceType: 'HTML', color: '#3a5a9b',
      sourceUrl: 'https://www.mobil.co.nz/en-nz/commercial-fuels/terminal-gate' },
  ];

  // What each supplier actually publishes at each active region. This is real
  // market structure (confirmed against live documents), not a placeholder —
  // Gull genuinely has no Wiri terminal; BP genuinely doesn't sell 95 at
  // Mount Maunganui. The UI must show absence honestly rather than padding it.
  const AVAILABILITY = {
    GULL:  { AUCKLAND_WIRI: [],                                    MOUNT_MAUNGANUI: ['REGULAR_91', 'PREMIUM_95', 'DIESEL'] },
    Z:     { AUCKLAND_WIRI: ['REGULAR_91', 'PREMIUM_95', 'DIESEL'], MOUNT_MAUNGANUI: ['REGULAR_91', 'PREMIUM_95', 'DIESEL'] },
    BP:    { AUCKLAND_WIRI: ['REGULAR_91', 'PREMIUM_95', 'DIESEL'], MOUNT_MAUNGANUI: ['REGULAR_91', 'DIESEL'] },
    MOBIL: { AUCKLAND_WIRI: ['REGULAR_91', 'PREMIUM_95', 'DIESEL'], MOUNT_MAUNGANUI: ['REGULAR_91', 'PREMIUM_95', 'DIESEL'] },
  };

  const supplierById = Object.fromEntries(SUPPLIERS.map((s) => [s.id, s]));
  const regionById = Object.fromEntries(REGIONS.map((r) => [r.id, r]));
  const productById = Object.fromEntries(PRODUCTS.map((p) => [p.id, p]));

  // ---------------------------------------------------------------- seed rows
  // [supplierId, regionId, terminalName(original wording), operator,
  //  productId, currentValue, previousValue|null, effectiveDate,
  //  previousEffectiveDate|null, extractionMethod, sourceDocumentUrl, note]
  const RAW = [
    // GULL — Mount Maunganui only, single terminal, non-sparse
    ['GULL','MOUNT_MAUNGANUI','TNZ Mt Maunganui','TNZ','REGULAR_91',280.79,294.82,'2026-08-14','2026-08-07','TEXT_EXACT_ARITY',
      'https://gull.nz/assets/Uploads/250e5ad555/TGP-effective-14AUG26.pdf', null],
    ['GULL','MOUNT_MAUNGANUI','TNZ Mt Maunganui','TNZ','PREMIUM_95',291.37,306.03,'2026-08-14','2026-08-07','TEXT_EXACT_ARITY',
      'https://gull.nz/assets/Uploads/250e5ad555/TGP-effective-14AUG26.pdf', null],
    ['GULL','MOUNT_MAUNGANUI','TNZ Mt Maunganui','TNZ','DIESEL',238.86,256.78,'2026-08-14','2026-08-07','TEXT_EXACT_ARITY',
      'https://gull.nz/assets/Uploads/250e5ad555/TGP-effective-14AUG26.pdf', null],

    // Z — Wiri
    ['Z','AUCKLAND_WIRI','Wiri Oil Service Limited (WOSL)','WOSL','REGULAR_91',274.04,289.64,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],
    ['Z','AUCKLAND_WIRI','Wiri Oil Service Limited (WOSL)','WOSL','PREMIUM_95',292.76,307.88,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],
    ['Z','AUCKLAND_WIRI','Wiri Oil Service Limited (WOSL)','WOSL','DIESEL',242.46,257.97,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],
    // Z — Mount Maunganui NORTH and SOUTH are genuinely separate terminals
    // (see /people/architecture note: flattening these loses real distinct prices).
    ['Z','MOUNT_MAUNGANUI','Z Mount Maunganui North','Z','REGULAR_91',271.99,287.60,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],
    ['Z','MOUNT_MAUNGANUI','Z Mount Maunganui North','Z','PREMIUM_95',292.10,307.22,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],
    ['Z','MOUNT_MAUNGANUI','Z Mount Maunganui North','Z','DIESEL',239.28,254.79,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],
    ['Z','MOUNT_MAUNGANUI','Z Mount Maunganui South','Z','REGULAR_91',271.99,287.60,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],
    ['Z','MOUNT_MAUNGANUI','Z Mount Maunganui South','Z','PREMIUM_95',292.10,307.22,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],
    ['Z','MOUNT_MAUNGANUI','Z Mount Maunganui South','Z','DIESEL',239.28,254.79,'2026-08-12','2026-08-05','TEXT_EXACT_ARITY',
      'https://znz-webbackendassets-s3bucket-prod.s3.ap-southeast-2.amazonaws.com/public/zenergy/for-businesses/documents/TGP-Price-20260812.pdf', null],

    // BP — Wiri (full, non-sparse)
    ['BP','AUCKLAND_WIRI','Wiri','WOSL','REGULAR_91',282.58,279.27,'2026-08-14','2026-08-11','TEXT_EXACT_ARITY',
      'https://www.bp.com/content/dam/bp/country-sites/en_nz/new-zealand/home/documents/tgp-pricing-uploads/terminal-gate-prices-nz.pdf', null],
    ['BP','AUCKLAND_WIRI','Wiri','WOSL','PREMIUM_95',296.38,293.07,'2026-08-14','2026-08-11','TEXT_EXACT_ARITY',
      'https://www.bp.com/content/dam/bp/country-sites/en_nz/new-zealand/home/documents/tgp-pricing-uploads/terminal-gate-prices-nz.pdf', null],
    ['BP','AUCKLAND_WIRI','Wiri','WOSL','DIESEL',250.25,247.18,'2026-08-14','2026-08-11','TEXT_EXACT_ARITY',
      'https://www.bp.com/content/dam/bp/country-sites/en_nz/new-zealand/home/documents/tgp-pricing-uploads/terminal-gate-prices-nz.pdf', null],
    // BP — Mount Maunganui: sparse in the raw text, resolved by coordinate
    // extraction. Two DIFFERENT terminals (different operators), each selling
    // one grade. No Premium 95 row exists because BP doesn't sell it here.
    ['BP','MOUNT_MAUNGANUI','Mt Maunganui BP','NZOSL','DIESEL',250.66,245.30,'2026-08-14','2026-08-11','PDF_COORDINATE',
      'https://www.bp.com/content/dam/bp/country-sites/en_nz/new-zealand/home/documents/tgp-pricing-uploads/terminal-gate-prices-nz.pdf',
      'Resolved via coordinate extraction — text extraction alone could not safely assign this cell.'],
    ['BP','MOUNT_MAUNGANUI','Mt Maunganui TNZ','TNZ','REGULAR_91',282.85,null,'2026-08-14',null,'PDF_COORDINATE',
      'https://www.bp.com/content/dam/bp/country-sites/en_nz/new-zealand/home/documents/tgp-pricing-uploads/terminal-gate-prices-nz.pdf',
      'Resolved via coordinate extraction. No prior-week observation of this specific terminal is on file.'],

    // MOBIL — HTML table, both regions, no prior week captured yet
    ['MOBIL','AUCKLAND_WIRI','Wiri','WOS','REGULAR_91',289.61,null,'2026-08-15',null,'HTML_TABLE',
      'https://www.mobil.co.nz/en-nz/commercial-fuels/terminal-gate', 'First automated capture — no prior observation on file.'],
    ['MOBIL','AUCKLAND_WIRI','Wiri','WOS','PREMIUM_95',302.17,null,'2026-08-15',null,'HTML_TABLE',
      'https://www.mobil.co.nz/en-nz/commercial-fuels/terminal-gate', 'First automated capture — no prior observation on file.'],
    ['MOBIL','AUCKLAND_WIRI','Wiri','WOS','DIESEL',253.71,null,'2026-08-15',null,'HTML_TABLE',
      'https://www.mobil.co.nz/en-nz/commercial-fuels/terminal-gate', 'First automated capture — no prior observation on file.'],
    ['MOBIL','MOUNT_MAUNGANUI','Mount Maunganui','Mobil','REGULAR_91',288.57,null,'2026-08-15',null,'HTML_TABLE',
      'https://www.mobil.co.nz/en-nz/commercial-fuels/terminal-gate', 'First automated capture — no prior observation on file.'],
    ['MOBIL','MOUNT_MAUNGANUI','Mount Maunganui','Mobil','PREMIUM_95',301.13,null,'2026-08-15',null,'HTML_TABLE',
      'https://www.mobil.co.nz/en-nz/commercial-fuels/terminal-gate', 'First automated capture — no prior observation on file.'],
    ['MOBIL','MOUNT_MAUNGANUI','Mount Maunganui','Mobil','DIESEL',252.56,null,'2026-08-15',null,'HTML_TABLE',
      'https://www.mobil.co.nz/en-nz/commercial-fuels/terminal-gate', 'First automated capture — no prior observation on file.'],
  ];

  function gstWordingFor(supplierId) {
    switch (supplierId) {
      case 'GULL': return 'Prices quoted are inclusive of GST';
      case 'Z': return 'Are NZ cents per litre including ETS and all applicable taxes (NLTF, PEFML, ACC, LAFT, RFT and GST)';
      case 'BP': return 'Includes All Taxes (Excise, PEFML, ACC, Carbon, LAFT, GST)';
      case 'MOBIL': return 'All quoted TGPs include: Excise duty, PEFML, ACC Levy, NLTF, LAFT, RFT where relevant, ETS Carbon Cost, GST';
      default: return null;
    }
  }

  function buildRecordId(supplierId, terminalName, productId, effectiveDate) {
    return [supplierId, terminalName.replace(/\s+/g, '_').toUpperCase(), productId, effectiveDate].join('|');
  }

  function buildCurrentPrices() {
    return RAW.map((row) => {
      const [supplierId, regionId, terminalName, operator, productId, current, previous,
        effectiveDate, previousEffectiveDate, extractionMethod, sourceDocumentUrl, note] = row;

      const supplier = supplierById[supplierId];
      const region = regionById[regionId];
      const product = productById[productId];
      const delta = (typeof previous === 'number') ? +(current - previous).toFixed(2) : null;
      const pct = (typeof previous === 'number' && previous !== 0) ? +((delta / previous) * 100).toFixed(2) : null;

      return {
        recordId: buildRecordId(supplierId, terminalName, productId, effectiveDate),
        supplierId, supplierName: supplier.name, supplierColor: supplier.color, sourceType: supplier.sourceType,
        regionId, regionLabel: region.label,
        terminalName, operator,
        productId, productName: product.label, productShort: product.shortLabel,
        currentValue: current,
        previousValue: previous,
        previousEffectiveDate,
        change: delta,
        changePct: pct,
        direction: delta === null ? 'NEW' : delta > 0 ? 'UP' : delta < 0 ? 'DOWN' : 'FLAT',
        unit: 'NZ_CENTS_PER_LITRE',
        gstStatus: 'included',
        gstSourceWording: gstWordingFor(supplierId),
        effectiveDate,
        retrievedAt: '2026-08-16T07:12:00+12:00',
        sourceUrl: supplier.sourceUrl,
        sourceDocumentUrl,
        extractionMethod,
        validationStatus: 'PUBLISHED',
        note,
      };
    });
  }

  // ---------------------------------------------------------------- history
  // Weekly series per (supplier, region, product) that AVAILABILITY permits.
  // Anchored at the two real observations, then walked backward synthetically.
  function buildHistory(currentPrices, weeksBack) {
    const out = [];
    const grouped = {};
    currentPrices.forEach((r) => {
      const key = [r.supplierId, r.regionId, r.terminalName, r.productId].join('::');
      (grouped[key] = grouped[key] || []).push(r);
    });

    Object.entries(grouped).forEach(([key, recs]) => {
      const r = recs[0];
      const rng = mulberry32(hashSeed(key));
      const points = [];

      // Real anchor points first.
      points.push({ date: r.effectiveDate, value: r.currentValue });
      let anchorValue = r.currentValue;
      let anchorDate = r.effectiveDate;
      if (typeof r.previousValue === 'number') {
        points.push({ date: r.previousEffectiveDate, value: r.previousValue });
        anchorValue = r.previousValue;
        anchorDate = r.previousEffectiveDate;
      }

      // Walk backward synthetically, one point per week.
      let value = anchorValue;
      let date = new Date(anchorDate + 'T00:00:00Z');
      for (let i = points.length; i < weeksBack; i++) {
        date = new Date(date.getTime() - 7 * 86400000);
        const drift = (rng() - 0.52) * 0.02;      // slight long-run downward drift
        const noise = (rng() - 0.5) * 0.03;        // weekly volatility ~1.5% each way
        value = Math.max(150, Math.min(340, value * (1 - drift - noise)));
        points.push({ date: date.toISOString().slice(0, 10), value: +value.toFixed(2) });
      }

      points.forEach((p) => out.push({
        supplierId: r.supplierId, supplierName: r.supplierName, supplierColor: r.supplierColor,
        regionId: r.regionId, regionLabel: r.regionLabel, terminalName: r.terminalName,
        productId: r.productId, productName: r.productName,
        effectiveDate: p.date, value: p.value,
      }));
    });

    return out.sort((a, b) => a.effectiveDate.localeCompare(b.effectiveDate));
  }

  // ---------------------------------------------------------------- AIP
  // Synthetic weekday-only AIP series (AUD cents/litre), two grades. Trend is
  // deliberately downward over the final fortnight so the Market Direction
  // demo has a real, explicable non-neutral state to show — see calculations.js.
  function buildAip(days) {
    const rng = mulberry32(hashSeed('AIP-ULP-DIESEL-2026'));
    const out = [];
    let ulp = 168.4, diesel = 172.1;
    let date = new Date();
    const series = [];
    while (series.length < days) {
      const dow = date.getUTCDay();
      if (dow !== 0 && dow !== 6) series.push(new Date(date));
      date = new Date(date.getTime() - 86400000);
    }
    series.reverse();
    series.forEach((d, i) => {
      const fromEnd = series.length - i;
      const trend = fromEnd <= 12 ? 0.0035 : -0.0006; // downward push in the most recent ~12 weekdays
      ulp = Math.max(120, ulp * (1 - trend - (rng() - 0.5) * 0.01));
      diesel = Math.max(120, diesel * (1 - trend - (rng() - 0.5) * 0.009));
      out.push({
        date: d.toISOString().slice(0, 10),
        ulp: +ulp.toFixed(2),
        diesel: +diesel.toFixed(2),
        unit: 'AU_CENTS_PER_LITRE',
        source: 'https://www.aip.com.au/pricing/terminal-gate-prices',
      });
    });
    return out;
  }

  // ---------------------------------------------------------------- documents / runs / errors
  function buildDocuments(currentPrices) {
    const seen = new Set();
    const docs = [];
    currentPrices.forEach((r) => {
      const k = r.sourceDocumentUrl + r.effectiveDate;
      if (seen.has(k)) return;
      seen.add(k);
      docs.push({
        supplierId: r.supplierId, supplierName: r.supplierName,
        documentUrl: r.sourceDocumentUrl, effectiveDate: r.effectiveDate,
        retrievedAt: r.retrievedAt,
        hash: hashSeed(k).toString(16).padStart(8, '0') + hashSeed(k + 'x').toString(16).padStart(8, '0'),
        productsFound: [...new Set(currentPrices.filter((x) => x.sourceDocumentUrl === r.sourceDocumentUrl && x.effectiveDate === r.effectiveDate).map((x) => x.productShort))],
        terminalsFound: [...new Set(currentPrices.filter((x) => x.sourceDocumentUrl === r.sourceDocumentUrl && x.effectiveDate === r.effectiveDate).map((x) => x.terminalName))],
        status: 'PROCESSED',
      });
    });
    return docs.sort((a, b) => b.effectiveDate.localeCompare(a.effectiveDate));
  }

  function buildAutomationRuns() {
    const now = new Date('2026-08-16T07:12:00+12:00');
    const fmt = (d) => d.toISOString();
    const nextWeekday = (from) => {
      const d = new Date(from.getTime() + 86400000);
      while (d.getUTCDay() === 0 || d.getUTCDay() === 6) d.setUTCDate(d.getUTCDate() + 1);
      d.setUTCHours(18, 0, 0, 0); // ~06:00 NZST next day
      return d;
    };
    return [
      { supplierId: 'GULL', supplierName: 'Gull New Zealand', connector: 'PDF', lastCheck: fmt(now),
        lastSuccess: fmt(now), status: 'OK', productsFound: 3, terminalsFound: 1,
        lastError: null, nextCheck: fmt(nextWeekday(now)) },
      { supplierId: 'Z', supplierName: 'Z Energy', connector: 'PDF', lastCheck: fmt(now),
        lastSuccess: fmt(now), status: 'OK', productsFound: 3, terminalsFound: 2,
        lastError: null, nextCheck: fmt(nextWeekday(now)) },
      { supplierId: 'BP', supplierName: 'BP New Zealand', connector: 'PDF', lastCheck: fmt(now),
        lastSuccess: fmt(now), status: 'WARNING', productsFound: 2, terminalsFound: 2,
        lastError: 'Mount Maunganui rows required coordinate extraction — text pass alone was ambiguous.',
        nextCheck: fmt(nextWeekday(now)) },
      { supplierId: 'MOBIL', supplierName: 'Mobil', connector: 'HTML', lastCheck: fmt(now),
        lastSuccess: fmt(now), status: 'OK', productsFound: 3, terminalsFound: 2,
        lastError: null, nextCheck: fmt(nextWeekday(now)) },
      { supplierId: 'AIP', supplierName: 'AIP (AU market indicator)', connector: 'HTML', lastCheck: fmt(now),
        lastSuccess: fmt(now), status: 'OK', productsFound: 2, terminalsFound: 0,
        lastError: null, nextCheck: fmt(nextWeekday(now)) },
    ];
  }

  function buildErrors() {
    return [
      { id: 'e1', severity: 'RESOLVED', supplierId: 'BP', date: '2026-08-14',
        message: 'Mount Maunganui: 2 rows carried a single value each — positional assignment would have guessed the grade. Withheld pending coordinate extraction.',
        status: 'Resolved', resolution: 'Coordinate extraction implemented; both rows now publish correctly.' },
      { id: 'e2', severity: 'INFO', supplierId: 'MOBIL', date: '2026-08-15',
        message: 'First automated capture for Mobil. No prior-week figure exists for change calculation yet.',
        status: 'Needs Review', resolution: null },
      { id: 'e3', severity: 'WARNING', supplierId: 'Z', date: '2026-08-12',
        message: 'Christchurch (Lyttelton) row published Regular 91 and Diesel only — no Premium 95 cell present in source. Row is correct as published; no action needed.',
        status: 'Ignored', resolution: 'Confirmed against source: Z does not sell Premium 95 at Lyttelton.' },
      { id: 'e4', severity: 'ERROR', supplierId: 'GULL', date: '2026-07-30',
        message: 'Source document link changed format (hash directory rotated). Connector located the new PDF automatically from the landing page; no manual fix required.',
        status: 'Resolved', resolution: 'findLatestSource() re-resolved the new URL on the next scheduled check.' },
    ];
  }

  // ---------------------------------------------------------------- assemble
  const currentPrices = buildCurrentPrices();
  const priceHistory = buildHistory(currentPrices, 60); // ~14 months, weekly
  const aipPrices = buildAip(90);
  const documents = buildDocuments(currentPrices);
  const automationRuns = buildAutomationRuns();
  const errors = buildErrors();

  global.TGP = global.TGP || {};
  global.TGP.config = { suppliers: SUPPLIERS, regions: REGIONS, products: PRODUCTS, availability: AVAILABILITY };
  global.TGP.data = { currentPrices, priceHistory, aipPrices, documents, automationRuns, errors };
  global.TGP.lookup = { supplierById, regionById, productById };
}(window));
